language: python
python:
    - "2.7"
    - "3.2"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq ruby-sass
install:
    - pip install nose mock --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install --use-mirrors unittest2py3k; else pip install --use-mirrors unittest2; fi
    - pip install . --use-mirrors
    - pip install Markdown
    - pip install webassets
    - pip install cssmin
script: nosetests -s tests
notifications:
    irc:
        channels:
            - "irc.freenode.org#pelican"
        on_success: change
