language: python
python:
    - "2.7"
    - "3.3"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends asciidoc
 - sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/share/asciidoc/asciidocapi.py ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi
    - pip install .
    - pip install -r dev_requirements.txt
    - pip install nose-cov
script: nosetests -sv --with-coverage --cover-package=pelican pelican
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
    irc:
        channels:
            - "irc.freenode.org#pelican"
        on_success: change
